sonar.projectKey=Frontend-Galenos-Pro
sonar.projectName=Frontend Galenos Pro
sonar.projectVersion=1.0.0
sonar.host.url=http://localhost:9000

sonar.sources=src/app/features/farmacia/services,src/app/features/farmacia/components/alertas,src/app/features/farmacia/components/categorias,src/app/features/farmacia/components/inventario,src/app/features/farmacia/components/movimientos
sonar.exclusions=**/*.spec.ts,**/*.html

sonar.tests=src/app/features/farmacia
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/galenos-pro/lcov.info

sonar.sourceEncoding=UTF-8
